source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ConfigDeviceSDK_Example' do
  pod 'ConfigDeviceSDK', :path => '../'

  target 'ConfigDeviceSDK_Tests' do
    inherit! :search_paths

    
  end
end
